import { GoogleGenAI, Type, Schema } from "@google/genai";
import { SeoReport } from "../types";

const apiKey = process.env.API_KEY || '';

// Define the expected JSON schema for the model
const seoReportSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    overallScore: { type: Type.NUMBER, description: "Overall SEO score from 0 to 100" },
    metrics: {
      type: Type.OBJECT,
      properties: {
        performance: { type: Type.NUMBER, description: "Score 0-100 for speed/performance" },
        seo: { type: Type.NUMBER, description: "Score 0-100 for general SEO keywords/meta" },
        mobile: { type: Type.NUMBER, description: "Score 0-100 for mobile optimization" },
        links: { type: Type.NUMBER, description: "Score 0-100 for link structure" },
      },
      required: ["performance", "seo", "mobile", "links"],
    },
    summary: { type: Type.STRING, description: "A brief executive summary of the audit" },
    suggestions: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING },
          description: { type: Type.STRING },
          severity: { type: Type.STRING, enum: ["critical", "warning", "info"] },
          category: { type: Type.STRING, enum: ["speed", "keywords", "content", "mobile", "links"] },
        },
        required: ["title", "description", "severity", "category"],
      },
    },
    technicalDetails: {
      type: Type.OBJECT,
      properties: {
        loadTimeEstimate: { type: Type.STRING, description: "Estimated load time (e.g., '1.2s')" },
        mobileFriendly: { type: Type.BOOLEAN },
        sslSecure: { type: Type.BOOLEAN },
        internalLinksCount: { type: Type.NUMBER },
        externalLinksCount: { type: Type.NUMBER },
      },
      required: ["loadTimeEstimate", "mobileFriendly", "sslSecure", "internalLinksCount", "externalLinksCount"],
    },
  },
  required: ["overallScore", "metrics", "summary", "suggestions", "technicalDetails"],
};

export const analyzeUrl = async (url: string, planType: 'free' | 'pro'): Promise<SeoReport> => {
  if (!apiKey) {
    throw new Error("API Key not found");
  }

  const ai = new GoogleGenAI({ apiKey });

  let systemInstruction = "";
  let userPrompt = "";

  if (planType === 'pro') {
    // PRO PROMPT: Deep, technical, critical
    systemInstruction = "Você é um Consultor de SEO Sênior de Elite. Sua tarefa é realizar auditorias extremamente técnicas e detalhadas. Você deve ser rigoroso com as pontuações. Foque em Core Web Vitals, Schema Markup (JSON-LD), Estratégia de Conteúdo Semântico e Link Building avançado. Forneça recomendações que um desenvolvedor ou especialista em marketing experiente valorizaria.";
    
    userPrompt = `
      Realize uma auditoria SEO PROFISSIONAL (Nível Enterprise) para a URL: ${url}.
      
      Requisitos da Análise PRO:
      1. Seja crítico. Notas acima de 90 apenas para sites perfeitos.
      2. No resumo, inclua insights sobre autoridade de domínio potencial e lacunas de conteúdo.
      3. Nas sugestões, inclua termos técnicos específicos (ex: "Implementar lazy loading", "Corrigir CLS", "Otimizar TTFB", "Canonical tags").
      4. Sugira oportunidades de palavras-chave de cauda longa (long-tail).
      
      Retorne estritamente o JSON conforme o schema.
    `;
  } else {
    // FREE PROMPT: Basic, helpful, standard
    systemInstruction = "Você é um Assistente de SEO útil e amigável. Sua tarefa é realizar auditorias básicas para proprietários de pequenos sites. Seja encorajador, mas honesto. Foque no básico: Títulos, Descrições, Imagens pesadas e Texto.";
    
    userPrompt = `
      Realize uma auditoria SEO BÁSICA para a URL: ${url}.
      
      Requisitos da Análise Gratuita:
      1. Forneça uma visão geral sólida.
      2. Identifique os erros mais óbvios (ex: falta de H1, imagens sem alt, site lento).
      3. Mantenha a linguagem acessível para leigos.
      
      Retorne estritamente o JSON conforme o schema.
    `;
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: userPrompt,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        responseSchema: seoReportSchema,
        temperature: planType === 'pro' ? 0.3 : 0.5, // Pro is more deterministic/analytical
      },
    });

    const jsonText = response.text;
    if (!jsonText) throw new Error("No content generated");

    const data = JSON.parse(jsonText);
    
    // Add metadata not generated by AI
    return {
      ...data,
      url,
      planType,
      timestamp: new Date().toISOString(),
    };

  } catch (error) {
    console.error("Analysis failed:", error);
    throw new Error("Falha ao analisar o site. Verifique a URL e tente novamente.");
  }
};